import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
  Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  records_sidebar: [
    {
      type: 'autogenerated',
      dirName: 'records'
    },
  ],
  projects_sidebar: [
    'projects/index',
    {
      type: 'category',
      label: 'Layouts',
      collapsed: true,
      collapsible: true,
      items: [
        {type: 'autogenerated', dirName: 'projects/layouts'},
      ]
    }
  ],
  /*
  sb_p01: [
    {
      type: 'autogenerated',
      dirName: 'projects/sproutsense', //project 1 - sproutsense
    }
  ],
  sb_p02: [
    {
      type: 'autogenerated',
      dirName: 'projects/02', //project 2 - smart ambulance
    }
  ],
  sb_p03: [
    {
      type: 'autogenerated',
      dirName: 'projects/03',
    }
  ],
  sb_p04: [
    {
      type: 'autogenerated',
      dirName: 'projects/04',
    }
  ],
  */
  sb_p05: [
    {
      type: 'autogenerated',
      dirName: 'projects/ether', //project 5 - ether
    }
  ],
  /*
  sb_p06: [
    {
      type: 'autogenerated',
      dirName: 'projects/06',
    }
  ],
  sb_p07: [
    {
      type: 'autogenerated',
      dirName: 'projects/07',
    }
  ],
  */
};

export default sidebars;