import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
  Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  records_sidebar: [
    'records/index',
    {
      type: 'category',
      label: 'OS Lab',
      collapsed: true,
      collapsible: true,
      items: [
        {type: 'autogenerated', dirName: 'records/os'},
      ],
    },
    {
      type: 'category',
      label: 'DBMS Lab',
      collapsed: true,
      collapsible: true,
      items: [
        {type: 'autogenerated', dirName: 'records/dbms'},
      ]
    },
    {
      type: 'category',
      label: 'CN Lab',
      collapsed: true,
      collapsible: true,
      items: [
        {type: 'autogenerated', dirName: 'records/cn'},
      ],
    },
  ],
  projects_sidebar: [
    'projects/index',
    {
      type: 'category',
      label: 'Layouts',
      collapsed: true,
      collapsible: true,
      items: [
        {type: 'autogenerated', dirName: 'projects/layouts'},
      ]
    }
  ],
  /*
  sb_p01: [
    {
      type: 'autogenerated',
      dirName: 'projects/01',
    }
  ],
  sb_p02: [
    {
      type: 'autogenerated',
      dirName: 'projects/02',
    }
  ],
  sb_p03: [
    {
      type: 'autogenerated',
      dirName: 'projects/03',
    }
  ],
  sb_p04: [
    {
      type: 'autogenerated',
      dirName: 'projects/04',
    }
  ],
  */
  sb_p05: [
    {
      type: 'autogenerated',
      dirName: 'projects/05',
    }
  ],
  /*
  sb_p06: [
    {
      type: 'autogenerated',
      dirName: 'projects/06',
    }
  ],
  sb_p07: [
    {
      type: 'autogenerated',
      dirName: 'projects/07',
    }
  ],
  */
};

export default sidebars;